platform :osx, '10.9'

xcodeproj "NewtonCommanderBrowse"

target "Demo" do
  pod "newton-commander-browse", :path => "../newton-commander-browse.podspec"
end

target "NCWorker" do
  pod "newton-commander-browse", :path => "../newton-commander-browse.podspec"
end
