platform :osx, '10.9'

xcodeproj "NCWorker"

#pod "newton-commander-browse", :path => "../newton-commander-browse.podspec"
pod 'newton-commander-quark', :git => "https://github.com/neoneye/newton-commander-quark.git"

target "Demo" do
end

#target "DemoTests" do
#end
